name: readmission_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - pip:
    - mlflow>=2.1.0
    - xgboost>=1.6.0
    - scikit-learn>=1.0.0
    - pandas>=1.3.0
    - numpy>=1.20.0
    - fastapi>=0.95.0
    - uvicorn>=0.15.0
    - pydantic>=1.8.0